"""news表新增cover_url和type字段

Revision ID: 0b6ad7bded3d
Revises: 24b9abf5d2ff
Create Date: 2025-06-15 22:27:14.813157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b6ad7bded3d'
down_revision = '24b9abf5d2ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_url', sa.String(length=255), nullable=True, comment='图片路径'))
        batch_op.add_column(sa.Column('type', sa.String(length=16), nullable=False, comment='类型：normal普通，active活动'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('cover_url')

    # ### end Alembic commands ###
