"""修改chapter表增加status字段

Revision ID: 0fb11d2262b4
Revises: 93d194d56ff7
Create Date: 2025-06-20 10:54:56.304366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb11d2262b4'
down_revision = '93d194d56ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='published', nullable=False, comment='章节审核状态：published已发布、reviewing审核中、rejected未通过、pending待发布'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
