"""新增收藏表、评论表、关注表，并给 Book 增加收藏数量字段

Revision ID: 16ad571aac41
Revises: 7850265c1407
Create Date: 2025-06-07 16:47:51.064183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ad571aac41'
down_revision = '7850265c1407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_count', sa.Integer(), nullable=False, comment='被收藏数量'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('favorite_count')

    # ### end Alembic commands ###
