"""user表新增become_autauthor_at

Revision ID: 24b9abf5d2ff
Revises: 946751397a33
Create Date: 2025-06-15 21:36:32.339934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b9abf5d2ff'
down_revision = '946751397a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('become_author_at', sa.DateTime(), nullable=True, comment='成为作家的时间'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('become_author_at')

    # ### end Alembic commands ###
