"""为user表去除real_name字段

Revision ID: 32a9674139be
Revises: c4fd3f8f1885
Create Date: 2025-06-08 14:18:59.732990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32a9674139be'
down_revision = 'c4fd3f8f1885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('real_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('real_name', mysql.VARCHAR(length=8), nullable=True, comment='真实姓名'))

    # ### end Alembic commands ###
