"""修改chapter表和新增volume卷

Revision ID: 3788b409175e
Revises: 7cfd0d961186
Create Date: 2025-06-18 20:13:49.969959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3788b409175e'
down_revision = '7cfd0d961186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False, comment='所属书籍ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='卷标题'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volume_id', sa.Integer(), nullable=False, comment='所属卷ID'))
        batch_op.drop_constraint('chapter_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'volume', ['volume_id'], ['id'])
        batch_op.drop_column('book_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='所属小说ID'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('chapter_ibfk_1', 'book', ['book_id'], ['id'])
        batch_op.drop_column('volume_id')

    op.drop_table('volume')
    # ### end Alembic commands ###
