"""修改book表增加hero字段

Revision ID: 3bf7b43bf56f
Revises: e25f1fbd89e3
Create Date: 2025-06-19 20:58:42.841051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3bf7b43bf56f'
down_revision = 'e25f1fbd89e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hero', sa.String(length=64), nullable=True, comment='主角名'))
        batch_op.alter_column('theme_type',
               existing_type=mysql.VARCHAR(length=64),
               comment='主题分类标签',
               existing_comment='主题分类标签，如 青春甜宠、克苏鲁',
               existing_nullable=True)
        batch_op.alter_column('role_type',
               existing_type=mysql.VARCHAR(length=64),
               comment='角色分类标签',
               existing_comment='角色分类标签，如 多女主、总裁',
               existing_nullable=True)
        batch_op.alter_column('plot_type',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=64),
               comment='情节分类标签',
               existing_comment='情节分类标签，如 异世穿越、末日求生',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('plot_type',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=64),
               comment='情节分类标签，如 异世穿越、末日求生',
               existing_comment='情节分类标签',
               existing_nullable=True)
        batch_op.alter_column('role_type',
               existing_type=mysql.VARCHAR(length=64),
               comment='角色分类标签，如 多女主、总裁',
               existing_comment='角色分类标签',
               existing_nullable=True)
        batch_op.alter_column('theme_type',
               existing_type=mysql.VARCHAR(length=64),
               comment='主题分类标签，如 青春甜宠、克苏鲁',
               existing_comment='主题分类标签',
               existing_nullable=True)
        batch_op.drop_column('hero')

    # ### end Alembic commands ###
