"""新增收藏表、评论表、关注表，并给 Book 增加收藏数量字段

Revision ID: 3da66ed6e3b6
Revises: 16ad571aac41
Create Date: 2025-06-07 16:51:34.399414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da66ed6e3b6'
down_revision = '16ad571aac41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False, comment='关注者ID（谁去关注别人）'),
    sa.Column('followed_id', sa.Integer(), nullable=False, comment='被关注者ID（被谁关注）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='关注时间'),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followed_id', name='uniq_follow')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='评论者ID'),
    sa.Column('book_id', sa.Integer(), nullable=False, comment='小说ID'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父评论ID（用于楼中楼回复）'),
    sa.Column('content', sa.Text(), nullable=False, comment='评论内容'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='评论时间'),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='收藏者ID'),
    sa.Column('book_id', sa.Integer(), nullable=False, comment='被收藏的小说ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='收藏时间'),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'book_id', name='uniq_favorite')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    op.drop_table('comment')
    op.drop_table('follow')
    # ### end Alembic commands ###
