"""user表增加nickname字段增长

Revision ID: 3f270a9fc891
Revises: 6b0ed1ec421c
Create Date: 2025-06-09 22:58:15.359839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f270a9fc891'
down_revision = '6b0ed1ec421c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('nickname',
               existing_type=mysql.VARCHAR(length=8),
               type_=sa.String(length=16),
               existing_comment='昵称',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('nickname',
               existing_type=sa.String(length=16),
               type_=mysql.VARCHAR(length=8),
               existing_comment='昵称',
               existing_nullable=True)

    # ### end Alembic commands ###
