"""修改news表增加notice_url字段

Revision ID: 53d6e1d1e998
Revises: bd627ac95962
Create Date: 2025-06-19 16:39:24.943381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53d6e1d1e998'
down_revision = 'bd627ac95962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notice_url', sa.String(length=255), nullable=True, comment='资讯图路径'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('notice_url')

    # ### end Alembic commands ###
