"""user表增加masterpiece和author_level字段

Revision ID: 6b0ed1ec421c
Revises: dc7b551e172f
Create Date: 2025-06-08 21:45:17.191534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0ed1ec421c'
down_revision = 'dc7b551e172f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('masterpiece', sa.String(length=64), nullable=True, comment='代表作'))
        batch_op.add_column(sa.Column('author_level', sa.String(length=16), nullable=True, comment='作家等级'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('author_level')
        batch_op.drop_column('masterpiece')

    # ### end Alembic commands ###
