"""初始化小说系统表

Revision ID: 7850265c1407
Revises: d851abb000de
Create Date: 2025-06-04 21:08:59.006378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7850265c1407'
down_revision = 'd851abb000de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='作者ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='小说名称'),
    sa.Column('reader_type', sa.String(length=8), nullable=True, comment='读者性别 男生/女生'),
    sa.Column('category_type', sa.String(length=32), nullable=True, comment='分类主题 主题/角色/情节'),
    sa.Column('status', sa.String(length=16), nullable=True, comment='连载状态 已完结/连载中'),
    sa.Column('word_count', sa.Integer(), nullable=True, comment='实际字数'),
    sa.Column('word_count_range', sa.String(length=20), nullable=True, comment='字数区间'),
    sa.Column('tags', sa.String(length=255), nullable=True, comment='标签'),
    sa.Column('intro', sa.Text(), nullable=True, comment='简介'),
    sa.Column('cover_url', sa.String(length=255), nullable=True, comment='封面图片'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False, comment='所属小说ID'),
    sa.Column('chapter_num', sa.Integer(), nullable=False, comment='章节序号'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='章节标题'),
    sa.Column('word_count', sa.Integer(), nullable=True, comment='章节字数'),
    sa.Column('content', sa.Text(), nullable=False, comment='章节正文内容'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chapter')
    op.drop_table('book')
    # ### end Alembic commands ###
