"""news表新增is_banner字段

Revision ID: 7cfd0d961186
Revises: a21eb6d4cc24
Create Date: 2025-06-16 22:53:14.100567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7cfd0d961186'
down_revision = 'a21eb6d4cc24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banner', sa.Boolean(), nullable=False, comment='是否设为首页Banner图'))
        batch_op.alter_column('banner_url',
               existing_type=mysql.VARCHAR(length=255),
               comment='首页Banner路径',
               existing_comment='首页轮播图路径',
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=16),
               comment='类型：notice资讯，active活动',
               existing_comment='类型：normal普通，active活动',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=16),
               comment='类型：normal普通，active活动',
               existing_comment='类型：notice资讯，active活动',
               existing_nullable=False)
        batch_op.alter_column('banner_url',
               existing_type=mysql.VARCHAR(length=255),
               comment='首页轮播图路径',
               existing_comment='首页Banner路径',
               existing_nullable=True)
        batch_op.drop_column('is_banner')

    # ### end Alembic commands ###
