"""create user and other tables

Revision ID: 90825392be15
Revises: 
Create Date: 2025-05-27 12:33:07.136959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90825392be15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False, comment='手机号'),
    sa.Column('password', sa.String(length=60), nullable=True, comment='加密后的密码'),
    sa.Column('nickname', sa.String(length=8), nullable=False, comment='昵称'),
    sa.Column('role', sa.String(length=16), nullable=False, comment='用户角色（user/author/admin）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='注册时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
