"""news表新增banner_url字段

Revision ID: a21eb6d4cc24
Revises: 1875aaefd00c
Create Date: 2025-06-16 22:44:42.245528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a21eb6d4cc24'
down_revision = '1875aaefd00c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_url', sa.String(length=255), nullable=True, comment='首页轮播图路径'))
        batch_op.alter_column('cover_url',
               existing_type=mysql.VARCHAR(length=255),
               comment='封面图路径',
               existing_comment='图片路径',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('cover_url',
               existing_type=mysql.VARCHAR(length=255),
               comment='图片路径',
               existing_comment='封面图路径',
               existing_nullable=True)
        batch_op.drop_column('banner_url')

    # ### end Alembic commands ###
