"""修改comment表

Revision ID: a82cc6ce0926
Revises: 0fb11d2262b4
Create Date: 2025-06-20 13:23:26.720857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a82cc6ce0926'
down_revision = '0fb11d2262b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_to_user_id', sa.Integer(), nullable=True, comment='被@用户ID'))
        batch_op.create_foreign_key(None, 'user', ['reply_to_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reply_to_user_id')

    # ### end Alembic commands ###
