"""为user表新增real_name字段

Revision ID: c4fd3f8f1885
Revises: 3da66ed6e3b6
Create Date: 2025-06-08 14:13:02.757410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4fd3f8f1885'
down_revision = '3da66ed6e3b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('real_name', sa.String(length=8), nullable=True, comment='真实姓名'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('real_name')

    # ### end Alembic commands ###
