"""为user表新增signature字段

Revision ID: d430e29aebee
Revises: 32a9674139be
Create Date: 2025-06-08 14:32:57.234348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd430e29aebee'
down_revision = '32a9674139be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature', sa.String(length=255), nullable=True, comment='签名'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('signature')

    # ### end Alembic commands ###
