"""add avatar and nickname to user table

Revision ID: d851abb000de
Revises: 6f977f2836d2
Create Date: 2025-05-28 17:41:24.928119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd851abb000de'
down_revision = '6f977f2836d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('nickname',
               existing_type=mysql.VARCHAR(length=8),
               nullable=True,
               existing_comment='昵称')
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True,
               existing_comment='用户角色（user/author/admin）')
        batch_op.alter_column('avatar',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_comment='头像路径')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_comment='头像路径')
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=16),
               nullable=False,
               existing_comment='用户角色（user/author/admin）')
        batch_op.alter_column('nickname',
               existing_type=mysql.VARCHAR(length=8),
               nullable=False,
               existing_comment='昵称')

    # ### end Alembic commands ###
