"""user表增加life_photo字段

Revision ID: dc7b551e172f
Revises: c60df4d5e342
Create Date: 2025-06-08 17:42:28.654731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc7b551e172f'
down_revision = 'c60df4d5e342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('life_photo', sa.String(length=255), nullable=True, comment='生活照路径'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('life_photo')

    # ### end Alembic commands ###
