"""修改news表增加is_notice字段

Revision ID: e25f1fbd89e3
Revises: 53d6e1d1e998
Create Date: 2025-06-19 16:45:21.739242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e25f1fbd89e3'
down_revision = '53d6e1d1e998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_notice', sa.Boolean(), nullable=False, comment='是否notice资讯'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('is_notice')

    # ### end Alembic commands ###
